### ISSUE TITLE
Server, TGI and/or vLLM Support

### ISSUE THREAD

**Issue by RonanKMcGovern** [IST-DASLab/marlin#24]
Marlin looks great, but are there:
1. quantization scripts -  a quantize.py file that we can easily use to make models and push to HF
2. vLLM or TGI support. I see that https://github.com/neuralmagic/nm-vllm has some marlin support, so that's a start. Also, TGI seems to be looking at marlin support.

Even if there was a quantize.py script that would help a lot and make nn-vllm a possibility.

**Comment by qeternity** [comment]
Marlin support exists in vLLM, the Neural Magic team upstreamed it.

As for a quantization script, it's already part of AutoGPTQ.

**Comment by RonanKMcGovern** [comment]
I see, what about AWQ, could that be supported? Better quality than GPTQ?

**Comment by qeternity** [comment]
Sure, feel free to make any pull requests to the respective projects.

**Comment by dalistarh** [comment]
Hi, 

We do not plan to add AWQ support; one reason is that we haven't observed higher quantization quality for AWQ relative to GPTQ/Marlin when both methods are tuned. Here's an example on LLaMA-3-8B-Instruct (MMLU Zero-Shot Accuracy):

| Model                                 | Accuracy (%) |
|---------------------------------------|--------------|
| bf16                                  | 65.80        |
| RTN   g128                                | 60.80        |
| GPTQ 4bit g128  actorder                      | 63.40        |
| casperhansen/llama-3-8b-instruct-awq g128 | 63.30        |

As you can see, both methods perform essentially the same.

**Comment by RonanKMcGovern** [comment]
Thanks, nice that you did the benchmarking.

Can you just clarify what you mean by "tuned"? Thanks, Ronan

**Comment by RonanKMcGovern** [comment]
Many thanks.
